const ImagesObject =  {
    apples: "/images/apple.jpg"
    ,apricot: "/images/apricot.jpg"
    ,arugula: "/images/apricot.jpg"
    ,asparagus: "/images/asparagus.jpg"
    ,basil:"/images/basil.jpg"
    ,beans: "/images/bean.jpg"
    ,beets:"/images/beet.jpg"
    ,blackberries:"/images/blackberry.jpg" 
    ,broccoli:"/images/broccoli.jpg"
    ,cabbage:"/images/cabbage.jpg"
    ,cantaloupe:"/images/cantaloupe.jpg"
    ,carrots:"/images/carrot.jpg"
    ,cauliflower:"/images/cauliflower.jpg"
    ,chard:"/images/chard.jpg"
    ,cherries: "/images/cherries.jpg"
    ,chilePeppers:"./images/chilePepper.jpg"
    ,chive:"/images/chive.jpg"
    ,cilantro:"/images/cilantro.jpg"
    ,corn:"/images/corn.jpg"
    ,cucumbers:"/images/cucumber.jpg"
    ,currant:"/images/currant.jpg"
    ,dairy:"/images/dairy.jpg"
    ,dill:"/images/dill.jpg"
    ,eggs:"/images/egg.jpg"
    ,eggplant:"/images/eggplant.jpg"
    ,figs:"/images/fig.jpg"
    ,flowers:"/images/flower.jpg"
    ,garlic:"/images/garlic.jpg"
    ,grapes:"/images/grape.jpg"
    ,honey:"/images/honey.jpg"
    ,honeydew:"/images/honeydew.jpg"
    ,kale:"/images/kale.jpg"
    ,lavender:"/images/lavender.jpg"
    ,lettuce:"/images/lettuce.jpg"
    ,meat:"/images/meat.jpg"
    ,mint:"/images/mint.jpg"
    ,nectarines:"/images/nectarine.jpg"
    ,nuts:"/images/nut.jpg"
    ,onions:"/images/onion.jpg"
    ,oregano:"/images/oregano.jpg"
    ,parsley:"/images/parsley.jpg"
    ,peas:"/images/pea.jpg"
    ,peaches:"/images/peach.jpg"
    ,pears:"/images/pear.jpg"
    ,plums:"/images/plum.jpg"
    ,potatoes:"/images/potato.jpg"
    ,pumpkins:"/images/pumpkin.jpg"
    ,radishes:"/images/radish.jpg"
    ,raspberries: "/images/raspberry.jpg"
    ,rhubarb:"/images/rhubarb.jpg"
    ,rosemary:"/images/rosemary.jpg"
    ,sage:"/images/sage.jpg"
    ,spinach:"/images/spinach.jpg"
    ,strawberries:"/images/strawberry.jpg"
    ,squash:"/images/summerSquash.jpg"
    ,sweetPeppers:"/images/sweetPepper.jpg"
    ,sweetPotatoes:"/images/sweetPotato.jpg"
    ,thyme:"/images/thyme.jpg"
    ,tomatoes:"/images/tomato.jpg" 
    ,turnips:"/images/turnip.jpg"
    ,watermelons:"/images/watermelon.jpg"
    ,winterSquash:"/images/winterSquash.jpg"
    ,zucchini:"/images/zucchini.jpg"
}

export default ImagesObject;